# Generated by Django 5.2.3 on 2025-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
