# Generated by Django 5.2.3 on 2025-08-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_opinion_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='usuario',
            new_name='nombre',
        ),
    ]
